version: '3'
services:
  # MySQL
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./00_create_database.sql:/docker-entrypoint-initdb.d/00_create_database.sql
    ports:
    - 3306:3306
